### ISSUE TITLE
Залипает бот

### ISSUE THREAD

**Issue by NoAdO** [Kylmakalle/tgvkbot#43]
В какой-то момент бот перестаёт отправлять сообщения из Телеграмм в ВК в групповом чате куда он добавлен. В логах повторяющееся сообщение:
`WARNING:vk_messages:Longpoll id 1: {'ts': 1723203814, 'updates': []}`
Встречал такое "залипание" уже несколько раз, меняется ID сообщения но и всё. Полистал лог назад, время возникновения ошибки непонятно, повторяющиеся сообщения как выше начинаются с:
`DEBUG:aiogram:Make request: 'getUpdates' with data: {'timeout': 20, 'offset': 704602229} and files {}
DEBUG:aiogram:Response for getUpdates: [200] {"ok":true,"result":[]}
DEBUG:aiogram:Make request: 'getUpdates' with data: {'timeout': 20, 'offset': 704602229} and files {}
WARNING:vk_messages:Longpoll id 1: {'ts': 1679087997, 'updates': []}
DEBUG:aiogram:Response for getUpdates: [200] {"ok":true,"result":[]}
DEBUG:aiogram:Make request: 'getUpdates' with data: {'timeout': 20, 'offset': 704602229} and files {}
WARNING:vk_messages:Longpoll id 1: {'ts': 1679087997, 'updates': []}
DEBUG:aiogram:Response for getUpdates: [502] {"ok":false,"error_code":502,"description":"Bad Gateway"}
WARNING:aiogram.dispatcher:Polling is stopped.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Dispatcher.start_polling() done, defined at /root/.local/lib/python3.6/site-packages/aiogram/dispatcher/__init__.py:214> exception=TelegramAPIError('Bad Gateway',)>
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/aiogram/dispatcher/__init__.py", line 243, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/root/.local/lib/python3.6/site-packages/aiogram/bot/bot.py", line 83, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/.local/lib/python3.6/site-packages/aiogram/bot/base.py", line 136, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth)
  File "/root/.local/lib/python3.6/site-packages/aiogram/bot/api.py", line 195, in request
    return await _check_result(method, response)
  File "/root/.local/lib/python3.6/site-packages/aiogram/bot/api.py", line 119, in _check_result
    raise exceptions.TelegramAPIError(description)
aiogram.utils.exceptions.TelegramAPIError: Bad Gateway
WARNING:vk_messages:Longpoll id 1: {'ts': 1679087997, 'updates': []}
WARNING:vk_messages:Longpoll id 1: {'ts': 1679087997, 'updates': []}
WARNING:vk_messages:Longpoll id 1: {'ts': 1679087997, 'updates': []}`

Я так понимаю 200 это ок а вот после получения 502 начинаются проблемы. Я видел что недавно был коммит на обновление:
`tgvkbot#37 Bump pillow from 5.1.0 to 9.0.1 (https://github.com/Kylmakalle/tgvkbot/pull/37#issuecomment-1322934680)`
но у меня Докер установка и хотя в описании бота указано что
`на всякий случай фиксируются версии каждого коммита`
образ Докер последний раз обновлялся 4 месяца назад.

**Comment by NoAdO** [comment]
Баг никуда не делся. Решаю тупо создав .sh файл 
```#!/bin/bash

sudo docker restart kylmakalle_tgvkbot```
и запуская его раз в час.
