### ISSUE TITLE
ошибка развертки на c9.io

### ISSUE THREAD

**Issue by Artlant** [Kylmakalle/tgvkbot#8]
Привет.
получил токены и захотелось развернуть не в Heroku а в Cloud9. 
1) `$ git clone`
2) `$ sudo -H pip3 install -r requirements.txt`
как сделать pfuhepbnm template в Cloud9 у меня мозгов не хватило. Если кто знает прошу напишите.
и по этому я просто заменил переменные.
3) `
$ cat credentials.py 
import os
#token = os.environ['TELEGRAM_TOKEN']
#vk_app_id = os.environ['VK_APP']

token = "442407407:AAGeH7CXfu-ALsq3ZGJuhadc_XXXX"
vk_app_id = "6173XXX"
`
4) `$ python2/3 ./bot.by` - и тут вылезло:

`Important: use os.getenv(PORT, 8080) as the port and os.getenv(IP, 0.0.0.0) as the host in your scripts!

Traceback (most recent call last):
  File "/home/ubuntu/workspace/bot.py", line 17, in <module>
    from vk_messages import VkMessage, VkPolling
  File "/home/ubuntu/workspace/vk_messages.py", line 12, in <module>
    vk_tokens = redis.from_url(os.environ.get("REDIS_URL"))
  File "/usr/local/lib/python3.4/dist-packages/redis/utils.py", line 19, in from_url
    return Redis.from_url(url, db, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 486, in from_url
    connection_pool = ConnectionPool.from_url(url, db=db, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 838, in from_url
    if '?' in url.path and not url.query:
TypeError: 'str' does not support the buffer interface

Process exited with code: 1`

Помогите если можете. Или можете сделать clone Workspaces и потом расшарить (если такое возможно).
Просто я слишом тупой. Я не понимаю откуда достать модули VkMessage и как загрузить/установить app.json

**Comment by Kylmakalle** [comment]
Если у вас мало знаний и опыта, почему бы не воспользоваться уже готовой [инструкцией](https://asergey.me/tgvkbot/installation/) по деплою на хероку, буквально одним нажатием?

Для деплоя не на heroku пользуйтесь [этой](https://github.com/Kylmakalle/tgvkbot/tree/webhook) веткой и убедитесь что в воркспейсе есть redisdb как сервис

**Comment by Artlant** [comment]
При загрузки шаблона на Heroku обязательно нужно привязать свою карту. А я по этическим/религиозным не хочу этого делать. Отдавать комуто свой cvv код ну это не очень и безопасно.

А о другой ветки я не знал ней. Попробую, спасибо

**Comment by Artlant** [comment]
Зависимости установлены, сервер запущен. weebhook привязан. port url логи без ошибок. Но при отправке сообщений/команд в телеграм бот не реагирует. 

дальше вылезло ошибки:
```
Important: use os.getenv(PORT, 8080) as the port and os.getenv(IP, 0.0.0.0) as the host in your scripts!

Exception in thread supervisor:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:8080. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/workspace/bot.py", line 242, in thread_supervisor
    for uid in vk_tokens.scan_iter():
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 1489, in scan_iter
    cursor, data = self.scan(cursor=cursor, match=match, count=count)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 1476, in scan
    return self.execute_command('SCAN', *pieces)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:8080. Connection refused.

```
как выяснилось cloud9 может открыть только 8080/8081/8082 порты. Если указать в веб хуке порт то ошибка со стороны телеграма:
`Bad Request: bad webhook: Webhook can be set up only on ports 80, 88, 443 or 8443`

Запуск через питон2 проблема кодировки

**Comment by Artlant** [comment]
могу я вам дать пароль и логин к cloud9 в лс или im что бы посмотрели Или зашенить через LastPass. Знаю что наглость. Возможно стоит сделать более подробный мануал (для таких дегенератов как я) даже после выполнение установки - бот не работает.

**Comment by Kylmakalle** [comment]
> При загрузки шаблона на Heroku обязательно нужно привязать свою карту.

Совсем не обязательно, просто иначе бот будет работать ~20/30 дней месяца


По поводу c9, программа не может подключиться к базе redis. Попробуй подключиться через ``localhost:6379`` и убедиться что в воркспейсе впринципе установлен redis как сервис

**Comment by Artlant** [comment]
"Совсем не обязательно, просто иначе бот будет работать ~20/30 дней месяца"

боюсь что сейчас или именно моему региону, привязка карты обязательна. Отказ от привязки карты не допустим. Идет прерывание загрузки шаблона

![screenshot from 2017-09-05 11-13-14](https://user-images.githubusercontent.com/13064767/30051648-7c3af61a-922b-11e7-9949-a64f6bba54be.png)
![screenshot from 2017-09-05 11-13-01](https://user-images.githubusercontent.com/13064767/30051649-7c4796a4-922b-11e7-9871-5f65f7cbfa6a.png)

**Comment by Artlant** [comment]
$ sudo service redis-server start
Starting redis-server: redis-server.

> По поводу c9, программа не может подключиться к базе redis. Попробуй подключиться через localhost:6379 и убедиться что в воркспейсе впринципе установлен redis как сервис

я скорее наверно откажусь от сообщений vk в телеграме - неосилил. Спасибо что отвечали. Удачи в проекте. Возможно вам стоит задуматься о нем как о платном сервисе - кто знает
